#!/bin/bash
 
NAME=JDQD
DIR=/home/runner/work/software-engineering-project/software-engineering-project
USER=runner
GROUP=runner
WORKERS=3
WORKER_CLASS=uvicorn.workers.UvicornWorker
BIND=unix:$DIR/run/gunicorn.sock
LOG_LEVEL=error
 
cd $DIR
 
exec gunicorn main:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=- \
  --reload \
  --reload-engine='poll'
