on:
        push:
                branches:
                        - zxj-dev
                          
jobs:                     
       restart-job:
               name: restart job
               runs-on: ubuntu-latest
               steps:
                      - name: pwd
                        run: pwd
                      - name: restart supervisor
                        run: supervisorctl restart JDQD
