on:
        push:
                branches:
                        - zxj-dev
                          
jobs:                     
       restart-job:
               name: restart job
               runs-on: ubuntu-latest
               steps:
                        - uses: actions/checkout@v4
                        - run: echo hello > world.txt 
                                
                        # 发布到目标服务器
                        - name: deploy file
                          uses: wlixcc/SFTP-Deploy-Action@v1.2.4
                          with:
                                username: ${{ secrets.HOST }}
                                server: ${{ secrets.USERNAME }}
                                ssh_private_key: ${{ secrets.ALIYUN }} 
                                local_path: '.'
                                remote_path: '/home/fastapi-user/action_test'

