on:
        push:
                branches:
                        - zxj-dev
                          
jobs:                     
       restart-job:
               name: restart job
               runs-on: ubuntu-latest
               steps:
                - name: Checkout
                  uses: actions/checkout@v2
                - name: deploy file
                  uses: wlixcc/SFTP-Deploy-Action@v1.2.4
                  with:
                        username: ${{ secrets.REMOTE_HOST }}
                        server: ${{ secrets.REMOTE_USERNAME }}
                        ssh_private_key: ${{ secrets.ALIYUN }} 
                        remote_path: '/home/fastapi-user/action_test'


