on:
        push:
                branches:
                        - zxj-dev
                          
jobs:                     
       restart-job:
               name: restart job
               runs-on: ubuntu-latest
               steps:
                      - uses: actions/checkout@v4
                      - name: install super
                        run: sudo apt install supervisor -y
                      - name: ls
                        run: ls
                      - name: restart supervisor
                        run: sudo supervisorctl restart JDQD
