on:
        push:
                branches:
                        - zxj-dev
                          
jobs:                     
       restart-job:
               name: restart job
               runs-on: ubuntu-latest
               steps:
                      - name: enter venv
                        run: source .venv/bin/activate
                      - name: restart supervisor
                        run: supervisorctl restart JDQD
