on:
        push:
                branches:
                        - zxj-dev
                          
jobs:                     
       restart-job:
               name: restart job
               runs-on: ubuntu-latest
               steps:
                      - uses: actions/checkout@v4
                      - name: install super
                        run: sudo apt install supervisor -y
                      - name: pip
                        run: pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple some-package


                      - name: copy
                        run: |
                            chmod u+x gunicorn_start
                            sudo cp fastapi-app /etc/nginx/sites-available/fastapi-app
                            sudo cp JDQD.conf /etc/supervisor/conf.d/JDQD.conf

                      - name: restart supervisor
                        run: |
                            sudo supervisorctl reread
                            sudo supervisorctl update
                            sudo supervisorctl restart JDQD
                            sudo supervisorctl status JDQD
                            sudo ln -s /etc/nginx/sites-available/fastapi-app /etc/nginx/sites-enabled/
                            sudo nginx -t
                            sudo systemctl restart nginx
